# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c78187ec16166315f87cc00977874da40850520069c3217a8185268ca133453afde46f20ce3886d1894315eb834e3cc8ec1a03e56ac8237b741fc998454a3e2

test:
  secret_key_base: 7ea04f232e6f179cb945b733fc3b48e3f49e597c5eff66ee37fc065ed6a88ede7e26d7c1141c85396a41f815de8f18fd826b61744351552520d3e255a8d509cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
